"""add is_admin to users

Revision ID: 12e5fb94915e
Revises: 63ee4d3b6a00
Create Date: 2026-07-30 20:52:47.000961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e5fb94915e'
down_revision: Union[str, Sequence[str], None] = '63ee4d3b6a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default nötig, weil die Spalte NOT NULL ist und bereits Zeilen
    # existieren könnten — ohne Default würde das Upgrade auf einer nicht
    # leeren Tabelle fehlschlagen.
    op.add_column(
        "users", sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false())
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
